In [ ]:
# We are going to start TensorFlow Basics here
# boleh guna number, text

In [ ]:
import tensorflow as tf

In [ ]:
print(tf.__version__)

2.19.0


In [ ]:
# Creating Tensor with constant
# Function here that we can use to create
scalar=tf.constant(9)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=9>

In [ ]:
scalar.ndim

0

In [ ]:
vector=tf.constant([10,10]) #number 10,10 yang terbaik
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim #dimension

1

In [ ]:
matrix=tf.constant([[5,9],[9,11]]) #numpy array using 2 dimension ([5,9],[9,11])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5,  9],
       [ 9, 11]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
second_matrix=tf.constant([[5,7], #2 dimension array
                           [3,8],
                           [3,9],
                           [4,2],
                           [8,6]])

In [ ]:
second_matrix

<tf.Tensor: shape=(5, 2), dtype=int32, numpy=
array([[5, 7],
       [3, 8],
       [3, 9],
       [4, 2],
       [8, 6]], dtype=int32)>

In [ ]:
second_matrix.ndim

2

In [ ]:
third_matrix=tf.constant(
     [
    [[1,2,3],
    [2,4,5]],

    [[7,9,3],
    [10,4,5]],

    [[11,2,3],
    [2,4,15]]
              ])
third_matrix

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 2,  4,  5]],

       [[ 7,  9,  3],
        [10,  4,  5]],

       [[11,  2,  3],
        [ 2,  4, 15]]], dtype=int32)>

In [ ]:
second_matrix=tf.constant([[5.6,7.3],
                           [3.45,8.25],
                           [3.11,9.23],
                           [4.34,2.34],
                           [8.4,6.23]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[5.6  7.3 ]
 [3.45 8.25]
 [3.11 9.23]
 [4.34 2.34]
 [8.4  6.23]], shape=(5, 2), dtype=float32)


In [ ]:
#single number that means scalar
scalar=tf.constant(5)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [ ]:
# a number with direction (multiple number)
vector=tf.constant([10,10,20,30])
vector

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([10, 10, 20, 30], dtype=int32)>

In [ ]:
# a 2-D array of numbers
matrix=tf.constant([[10,20],[30,40]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10, 20],
       [30, 40]], dtype=int32)>

In [ ]:
# Tensor: an n-dimensional array of numbers
tensor=tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor

<tf.Tensor: shape=(2, 2, 2), dtype=int32, numpy=
array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]], dtype=int32)>

In [ ]:
# Find the shape , rank and size of the tensors
print("Scalar Information")
print("Shape:", scalar.shape)
print("Dimension:", scalar.ndim)
print("Rank:",tf.rank(scalar).numpy())
print("Size:", tf.size(scalar))

Scalar Information
Shape: ()
Dimension: 0
Rank: 0
Size: tf.Tensor(1, shape=(), dtype=int32)


In [ ]:
print("Vector Information")
print("Shape:",vector.shape)
print("Dimension:",vector.ndim)
print("Rank:",tf.rank(vector).numpy())
print("Size:",tf.size(vector))

Vector Information
Shape: (4,)
Dimension: 1
Rank: 1
Size: tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
print("Matrix Information")
print("Shape:",matrix.shape)
print("Dimension:",matrix.ndim)
print("Rank:",tf.rank(matrix).numpy())
print("Size:",tf.size(matrix))

Matrix Information
Shape: (2, 2)
Dimension: 2
Rank: 2
Size: tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
print("Tensor Information")
print("Shape:",tensor.shape)
print("Dimension:",tensor.ndim)
print("Rank:",tf.rank(tensor).numpy())
print("Size:",tf.size(tensor))

Tensor Information
Shape: (2, 2, 2)
Dimension: 3
Rank: 3
Size: tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
#creating tensor using variable
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor,unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [ ]:
changeable_tensor[0].assign(9)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([9, 7], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(15)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 15], dtype=int32)>

In [ ]:
changeable_tensor[1].assign(75)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([ 9, 75], dtype=int32)>

In [ ]:
unchangeable_tensor # takboleh tukar nombor dalam [] immutable

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>

In [ ]:
# unchangeable_tensor[0].assign[12]
# unchangeable_tensor
# this will be an error because you can't change constant tensor/ They are immutable i.e. unchangeable

In [ ]:
#Random tensors
random_tensor=tf.random.Generator.from_seed(42)
random_tensor=random_tensor.normal(shape=(3,2)) #3 rows, 2 columns
random_tensor

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [ ]:
random_tensor_2=tf.random.uniform(shape=(300,150),minval=0,maxval=1)
random_tensor_2

<tf.Tensor: shape=(300, 150), dtype=float32, numpy=
array([[0.80884504, 0.86811316, 0.7205219 , ..., 0.26774895, 0.7287158 ,
        0.8830614 ],
       [0.6288923 , 0.2437365 , 0.08263421, ..., 0.84046066, 0.8024949 ,
        0.8276979 ],
       [0.95914805, 0.2762072 , 0.36166203, ..., 0.08979023, 0.23612559,
        0.07618713],
       ...,
       [0.5759696 , 0.32862866, 0.76162136, ..., 0.78696644, 0.23831451,
        0.6385306 ],
       [0.5873865 , 0.4701625 , 0.48174787, ..., 0.6201174 , 0.9355053 ,
        0.8859726 ],
       [0.21270001, 0.92087007, 0.22799397, ..., 0.7774136 , 0.33607042,
        0.280429  ]], dtype=float32)>

In [ ]:
random_tensor_3=tf.random.Generator.from_seed(42)
random_tensor_3=random_tensor_3.normal(shape=(3,2))
random_tensor_4=tf.random.Generator.from_seed(42)
random_tensor_4=random_tensor_4.normal(shape=(3,2))
random_tensor_3,random_tensor_4

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>)

In [ ]:
# creating tensors using zeros
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [ ]:
tensor_zeros=tf.zeros(shape=(3,4),dtype=tf.dtypes.float32)
tensor_zeros

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [ ]:
# Tensors for all ones
tensor_ones=tf.zeros(shape=(3,4),dtype=tf.dtypes.int16)
tensor_ones

<tf.Tensor: shape=(3, 4), dtype=int16, numpy=
array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)>

In [ ]:
import numpy as np
numpy_Array=np.arange(1,25,dtype=np.int16)
numpy_Array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int16)

In [ ]:
tensor_numpy=tf.constant(numpy_Array,shape=(2,3,4))
tensor_numpy

<tf.Tensor: shape=(2, 3, 4), dtype=int16, numpy=
array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]]], dtype=int16)>

In [ ]:
print("Tensor Information")
print("Shape:",tensor_numpy.shape)
print("Dimension:",tensor_numpy.ndim)
print("Rank:",tf.rank(tensor_numpy).numpy())
print("Size:",tf.size(tensor_numpy))
print("DataType of elements: ",tensor_numpy.dtype)
print("Element along axis 0:", tensor_numpy.shape[0])
print("Element along axis 1:", tensor_numpy.shape[1])
print("Element along axis 2:", tensor_numpy.shape[2])
print("Total number of element: \t",tf.size(tensor_numpy).numpy())

Tensor Information
Shape: (2, 3, 4)
Dimension: 3
Rank: 3
Size: tf.Tensor(24, shape=(), dtype=int32)
DataType of elements:  <dtype: 'int16'>
Element along axis 0: 2
Element along axis 1: 3
Element along axis 2: 4
Total number of element: 	 24


In [ ]:
# Working with items of each dimension
# first three elements
tensor_numpy[:3,:3,:3]

<tf.Tensor: shape=(2, 3, 3), dtype=int16, numpy=
array([[[ 1,  2,  3],
        [ 5,  6,  7],
        [ 9, 10, 11]],

       [[13, 14, 15],
        [17, 18, 19],
        [21, 22, 23]]], dtype=int16)>

In [ ]:
#First two elements of each dimension
tensor_numpy[:2,:2,:2]

<tf.Tensor: shape=(2, 2, 2), dtype=int16, numpy=
array([[[ 1,  2],
        [ 5,  6]],

       [[13, 14],
        [17, 18]]], dtype=int16)>

In [ ]:
# Arthmetic Operations
#- Add
#- Sub
#- multiple
#- Div

NameError: name 'Add' is not defined

In [ ]:
tensor_one=tf.constant([[11,9],[2,5]])
tensor_one

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[11,  9],
       [ 2,  5]], dtype=int32)>

In [ ]:
#tensor_one+15
tf.add(tensor_one,15)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[26, 24],
       [17, 20]], dtype=int32)>

In [ ]:
#tensor_one-5
tf.subtract(tensor_one,5)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 6,  4],
       [-3,  0]], dtype=int32)>

In [ ]:
#tensor_one*2
tf.multiply(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[22, 18],
       [ 4, 10]], dtype=int32)>

In [ ]:
#tensor_one/2
tf.divide(tensor_one,2)

<tf.Tensor: shape=(2, 2), dtype=float64, numpy=
array([[5.5, 4.5],
       [1. , 2.5]])>

In [ ]:
tensor_new=tf.square(tensor_one)
tensor_new

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  81],
       [  4,  25]], dtype=int32)>

In [ ]:
second_matrix=tf.constant([[8,16],[64,8.5],
                           [625,9.23],
                           [125,2.34],
                           [169,144]],dtype=tf.float32)
print(second_matrix)

tf.Tensor(
[[  8.    16.  ]
 [ 64.     8.5 ]
 [625.     9.23]
 [125.     2.34]
 [169.   144.  ]], shape=(5, 2), dtype=float32)


In [ ]:
tf.sqrt(second_matrix)

<tf.Tensor: shape=(5, 2), dtype=float32, numpy=
array([[ 2.828427 ,  4.       ],
       [ 8.       ,  2.9154758],
       [25.       ,  3.0380914],
       [11.18034  ,  1.5297059],
       [13.       , 12.       ]], dtype=float32)>

In [ ]:
# Exercise Create two tensors with random values between 0 and 1 , shape is [6,300]
# Find out the following details:
# Number of elements
# Size,
# Rank,
# Shape

In [ ]:
import tensorflow as tf

In [ ]:
tensor_1=tf.random.uniform(shape=(6,300),minval=0,maxval=1)

print("Tensor 1 Information")
print("Shape:",tensor_1.shape)
print("Rank:",tf.rank(tensor_1).numpy())
print("Size:",tf.size(tensor_1))
print("Total number of element: \t",tf.size(tensor_1).numpy())

Tensor 1 Information
Shape: (6, 300)
Rank: 2
Size: tf.Tensor(1800, shape=(), dtype=int32)
Total number of element: 	 1800


In [ ]:
tensor_2=tf.random.uniform(shape=(6,300),minval=0,maxval=1)

print("Tensor 2 Information")
print("Shape:",tensor_2.shape)
print("Rank:",tf.rank(tensor_2).numpy())
print("Size:",tf.size(tensor_2))
print("Total number of element: \t",tf.size(tensor_2).numpy())

Tensor 2 Information
Shape: (6, 300)
Rank: 2
Size: tf.Tensor(1800, shape=(), dtype=int32)
Total number of element: 	 1800
