# Numpy Introduction and Usage
# we will use numpy in this jupyter notebook

# One Dimensional Array (1-D)

In [2]:
import numpy as np

In [6]:
array1=np.array([10,20,30,40,50])

In [7]:
print(array1)

[10 20 30 40 50]


# Two Dimensional Array (2-D)

In [8]:
array_two=np.array([[10,20,30],[40,50,70]])

In [9]:
print(array_two)

[[10 20 30]
 [40 50 70]]


# Three Dimensional Array (3-D Array)

In [12]:
array_three=np.array([[[10,20,30],[40,50,60]],[[10,20,30],[40,50,70]]])

In [13]:
print(array_three)

[[[10 20 30]
  [40 50 60]]

 [[10 20 30]
  [40 50 70]]]


In [14]:
# Find out Dimension of NumPy Array

In [15]:
print('First Array Dimension: \t', array1.ndim)

First Array Dimension: 	 1


In [16]:
print('Second Array Dimension: \t', array_two.ndim)

Second Array Dimension: 	 2


In [17]:
print('Third Array Dimension: \t', array_three.ndim)

Third Array Dimension: 	 3


# Task 1: Write and array of 5 students marks using Numpy
    ## Marks are: 80,70,75,99,89

In [24]:
import numpy as np

In [25]:
students_marks=np.array([80,70,75,99,89])

In [28]:
print('Array of Marks: ')
print(students_marks)

Array of Marks: 
[80 70 75 99 89]


# Task 2: Write an array to take marks of 5 students in 3 subjects using Numpy (use 2_D Array)
    ## Math, English, Chemistry
    ## [[50,45,49],[40,42,45],[35,40,67],[48,49,40],[34,56,73]]

In [30]:
array_marks_subject=np.array([[50,45,49],[40,42,45],[35,40,67],[48,49,40],[34,56,73]])
print('2 D Array Example')
print(array_marks_subject)

2 D Array Example
[[50 45 49]
 [40 42 45]
 [35 40 67]
 [48 49 40]
 [34 56 73]]


# Task 3: Write an array: to take Marks of 4 students in 3 subjects for two semester using Numpy
## Students Name are: 'Amit','Ara','Sha','Xi'
## Math, English Chemistry
## Two Semester: Sem1, Sem 2
## 4*3*2
## [[85,88]-Math [78,83]-English [90,95]-Chemistry] -Fist students, [[ ]]-second students
## [[[85,88],[78,79],[90,94]], [[73,64],[55,60],[89,84]], [[54,57],[64,69],[34,60]], [[76,79],[84,89],[92,90]]]

In [32]:
marks_subjects_sem=np.array([[[85,88],[78,79],[90,94]], [[73,64],[55,60],[89,84]], [[54,57],[64,69],[34,60]], [[76,79],[84,89],[92,90]]])

In [33]:
print(marks_subjects_sem)

[[[85 88]
  [78 79]
  [90 94]]

 [[73 64]
  [55 60]
  [89 84]]

 [[54 57]
  [64 69]
  [34 60]]

 [[76 79]
  [84 89]
  [92 90]]]


# Task 4: Write an array: to take weather of 2 cities in 3 days for three times in a day morning, noon, evening
## Cities Name are: 'Kuala Lumpur','Delhi
## Saturday, Sunday, Monday
## Three time slot: Morning, Noon, Evening

# Create one 3 D Array for this using Numpy and print it
# Kuala Lumpur:[[30,35,40],[25,28,26],[31,34,27]]
# Delhi: [[40,25,32],[16,32,34],[33,31,37]]]
# [[[30,35,40],[25,28,26],[31,34,27]],[[40,25,32],[16,32,34],[33,31,37]]]

In [44]:
weather_array=np.array([[[30,35,40],[25,28,26],[31,34,27]],[[40,25,32],[16,32,34],[33,31,37]]])

In [45]:
print(weather_array)

[[[30 35 40]
  [25 28 26]
  [31 34 27]]

 [[40 25 32]
  [16 32 34]
  [33 31 37]]]


# Basic Information
    ## Shape : rows and columns
    ## Size : number of elements
    ## Dimension : return dimension 1,2,3 ...
    ## 

In [46]:
print(array1)

[80 70 75 99 89]


In [47]:
print("Shape of array1 : ", array1.shape)

Shape of array1 :  (5,)


In [48]:
print("Size of array1 : ", array1.size)

Size of array1 :  5


In [49]:
print ('Dimension : ',array1.ndim)

Dimension :  1


In [50]:
print ('Data Type : ',array1.dtype)

Data Type :  int64


In [53]:
students=np.array(['Ali Munir Bin Zakwan','Shi','Xi','Meena','Zizi'])

In [54]:
print(students)

['Ali Munir Bin Zakwan' 'Shi' 'Xi' 'Meena' 'Zizi']


In [56]:
print("Shape of array: ",students.shape)

Shape of array:  (5,)


In [55]:
print('Numbers of students',students.size)

Numbers of students 5


In [57]:
print('Data Type: ',students.dtype)

Data Type:  <U20


# Mathematical Operational

In [58]:
print(array1)

[80 70 75 99 89]


In [59]:
total=np.sum(array1)

In [60]:
print(total)

413


In [62]:
print('Mean:',np.mean(array1))

Mean: 82.6


In [63]:
print('Min: ',np.min(array1))

Min:  70


In [64]:
print('Max: ',np.max(array1))

Max:  99


In [65]:
print('Index of min: ',np.argmin(array1))

Index of min:  1


In [66]:
print('Index of Max: ',np.argmax(array1))

Index of Max:  3


In [67]:
our_array=np.array([100,200,300,400,500,600,7000])

In [68]:
print(our_array)

[ 100  200  300  400  500  600 7000]


# Searching and sorting example in 1D Array

In [70]:
sorted_arr=np.sort(our_array)
print('*** Sorted Array ***')
print(sorted_arr)

*** Sorted Array ***
[ 100  200  300  400  500  600 7000]


In [71]:
print('Is there any item greater than 500?: ',np.any(sorted_arr>500))

Is there any item greater than 500?:  True


In [72]:
print('All greater than 500?: ',np.all(sorted_arr>500))

All greater than 500?:  False


In [73]:
print('Where values >500',np.where(sorted_arr>500))

Where values >500 (array([5, 6]),)


In [75]:
print('All number greater than 500')
for num in np.where(sorted_arr>500):
    print (num)

All number greater than 500
[5 6]


In [6]:
print(our_array)

[ 100  200  300  400  500  600 7000]


In [9]:
sorted_arr=np.sort(our_array)
print('All number greater than 500')
for num in sorted_arr>500:
    print (num)

All number greater than 500
False
False
False
False
False
True
True


In [10]:
selected_values=sorted_arr[sorted_arr>500]

In [11]:
print(selected_values)

[ 600 7000]


In [12]:
for num in selected_values:
    print(num)

600
7000


In [13]:
for num in sorted_arr[sorted_arr>500]:
    print(num)

600
7000


In [14]:
print(' ',sorted_arr[sorted_arr>500])

  [ 600 7000]


# Slicing 1 D Array
    1.To take elements from starting index to end index
    2.e.g. [start:end]

In [15]:
print(our_array)

[ 100  200  300  400  500  600 7000]


In [17]:
slice_our_arr=our_array[1:3]
print(slice_our_arr)

[200 300]


# starting from an index and going till last

In [18]:
print(our_array[3:])

[ 400  500  600 7000]


In [20]:
print(sorted_arr)

[ 100  200  300  400  500  600 7000]


In [23]:
slice_sorted_arr=sorted_arr[1:3]
print(slice_sorted_arr)

[200 300]


In [25]:
print(sorted_arr[3:])

[ 400  500  600 7000]


In [27]:
print(sorted_arr[:4]) 

[100 200 300 400]


In [28]:
print(sorted_arr[:5])

[100 200 300 400 500]


# Step
    # [start:end:step]
    #step: every step element

In [29]:
our_slice=sorted_arr[1:6:2]
print(our_slice)

[200 400 600]


In [31]:
print('Original Array')
print(sorted_arr)
print('Every third Element')
every_third_element=sorted_arr[::3]
print(every_third_element)

Original Array
[ 100  200  300  400  500  600 7000]
Every third Element
[ 100  400 7000]


# Slice Reverse

In [34]:
print('Original Array')
print(sorted_arr)
print('Reverse Array: ')
print(sorted_arr[::-1])

Original Array
[ 100  200  300  400  500  600 7000]
Reverse Array: 
[7000  600  500  400  300  200  100]


In [35]:
print('Last Five Elements')
print(sorted_arr[-5:])

Last Five Elements
[ 300  400  500  600 7000]


In [36]:
print('Slicing Done')

Slicing Done
